# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='DateofBirth',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='patronymic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sex',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='surname',
            field=models.TextField(null=True),
        ),
    ]
