# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181018_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='DateofBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='patronymic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sex',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
