# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sex',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, null=True),
        ),
    ]
