# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181018_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hairСolor',
            field=models.CharField(choices=[('блонд', 'блонд'), ('брюнет', 'брюнет'), ('шатен', 'шатен'), ('рыжий', 'рыжий'), ('русый', 'русый'), ('седой', 'седой')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
