# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181018_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favoriteAnimal',
            field=models.CharField(choices=[('Собачка', 'Собачка'), ('Кошечка', 'Кошечка'), ('нечто среднее', 'нечто среднее')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='hairСolor',
            field=models.CharField(choices=[('блонд', 'блонд'), ('брюнет', 'брюнет'), ('шатен', 'шатен'), ('рыжий', 'рыжий'), ('русый', 'русый'), ('седой', 'седой')], max_length=6, null=True),
        ),
    ]
