# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 11:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_haveanimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
