# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 11:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181018_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
