# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181018_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog/pic_folder/15709.jpg', upload_to='blog/pic_folder/'),
        ),
    ]
