# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181018_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='haveAnimal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
